language: go

go:
  - 1.10.x
  - 1.9.x

# Install glide
addons:
  apt:
    sources:
    - sourceline: 'ppa:masterminds/glide'
    packages:
    - glide

install:
  - make setup

script:
  - make test-ci
  - make build-all
